
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Metadata } from "next";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";



export const metadata: Metadata = {
  title: "NavKIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar/>
            
            {children}
            <Footer/>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
